name: Feature Request
description: Suggest a new feature or enhancement for KotaDB
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: ["jayminwest"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for similar feature requests
          required: true
        - label: I have read the project roadmap and MCP integration plan
          required: true
        - label: This feature aligns with the project's goals for LLM integration
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of KotaDB does this feature relate to?
      options:
        - Storage Engine
        - Index System (Primary, Trigram, Semantic)
        - MCP Server Integration
        - Query Language
        - Performance Optimization
        - Developer Experience
        - Documentation
        - Testing Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow significantly
        - High - Critical for adoption
        - Urgent - Blocking current work
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "I also considered..."

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial
      placeholder: |
        1. When using with Claude/GPT for...
        2. For knowledge management scenarios like...
        3. In production environments where...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Suggestions
      description: If you have ideas about how this could be implemented, please share them
      placeholder: "This could be implemented by..."

  - type: checkboxes
    id: implementation-offer
    attributes:
      label: Implementation
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to test this feature
        - label: I would be willing to write documentation for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
