name: CI

on:
  push:
    branches: [ main, develop, 'release/**', 'hotfix/**' ]
  pull_request:
    branches: [ main, develop ]

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  # Optimize for CI performance
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_BUILD_JOBS: 4  # Increased from 2
  # Enable better test parallelism
  RUST_TEST_THREADS: 4  # New: explicit thread count

jobs:
  # Quick format check - fails fast
  format:
    name: Format Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    
    - name: Check formatting
      run: cargo fmt --all -- --check

  # Clippy check - runs in parallel with format
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"  # Share with build job
    
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  # Central build job that other tests depend on
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies and build artifacts
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"
    
    - name: Build all targets
      run: |
        cargo build --release --all-features
        cargo test --release --no-run --all-features
    
    - name: Upload test binaries
      uses: actions/upload-artifact@v4
      with:
        name: test-binaries
        path: |
          target/release/deps/*-*
          target/release/kotadb
        retention-days: 1
  
  # Unit tests - depends on build
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"
    
    - name: Download test binaries
      uses: actions/download-artifact@v4
      with:
        name: test-binaries
        path: target/release/deps
    
    - name: Run unit tests
      run: |
        cargo test --lib --release --all-features
      env:
        RUST_LOG: error
        CI: true
    
    - name: Run doc tests
      run: cargo test --doc --release --all-features

  # Security audit - can run in parallel
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache cargo-audit
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-audit
        key: cargo-audit-${{ runner.os }}-v2
    
    - name: Install cargo-audit
      run: |
        if [ ! -f ~/.cargo/bin/cargo-audit ]; then
          cargo install cargo-audit --locked
        fi
    
    - name: Security audit
      run: cargo audit
      continue-on-error: true  # Don't fail on advisories

  # Core integration tests - basic functionality
  integration-core:
    name: Integration Tests (Core)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 8
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"
    
    - name: Run core integration tests
      run: |
        cargo test --test 'file_storage*' --test 'builder*' --test 'validated_types*' \
                   --test 'data_integrity*' --test 'unicode_handling*' --test 'storage_index*' \
                   --release --features bench
      env:
        RUST_LOG: error
        CI: true
        RUST_TEST_THREADS: 4

  # Index integration tests - split from stress
  integration-index:
    name: Integration Tests (Index)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10  # Increased from 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"
    
    - name: Run index integration tests
      run: |
        cargo test --test 'primary_index*' --test 'btree*' --test 'test_btree*' \
                   --test 'query_routing*' --test 'bulk_operations*' \
                   --release --features bench
      env:
        RUST_LOG: error
        CI: true
        RUST_TEST_THREADS: 4

  # Heavy stress tests - split into two jobs
  integration-stress-1:
    name: Integration Tests (Stress Part 1)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10  # Increased from 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"
    
    - name: Run stress tests part 1
      run: |
        cargo test --test 'concurrent_stress*' --test 'concurrent_access*' \
                   --release --features bench
      env:
        RUST_LOG: error
        CI: true
        RUST_TEST_THREADS: 4

  integration-stress-2:
    name: Integration Tests (Stress Part 2)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10  # Increased from 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"
    
    - name: Run stress tests part 2
      run: |
        cargo test --test 'index_stress*' --test 'chaos*' --test 'adversarial*' \
                   --test 'complexity_comparison*' --test '*performance*' \
                   --release --features bench
      env:
        RUST_LOG: error
        CI: true
        RUST_TEST_THREADS: 4

  # System integration tests
  integration-system:
    name: Integration Tests (System)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10  # Increased from 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"
    
    - name: Download built binary
      uses: actions/download-artifact@v4
      with:
        name: test-binaries
        path: target/release
    
    - name: Make binary executable
      run: chmod +x target/release/kotadb
    
    - name: Run system integration tests
      run: |
        cargo test --test 'cli_path*' --test 'http_server*' --test 'observability*' \
                   --test 'production_configuration*' --test 'system_resilience*' \
                   --release --features bench
      env:
        RUST_LOG: error
        CI: true
        RUST_TEST_THREADS: 4

  # Integration tests summary - required by branch protection
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [integration-core, integration-index, integration-stress-1, integration-stress-2, integration-system]
    if: always()
    timeout-minutes: 1
    steps:
    - name: Check integration test results
      run: |
        if [[ "${{ needs.integration-core.result }}" == "failure" ]] || \
           [[ "${{ needs.integration-index.result }}" == "failure" ]] || \
           [[ "${{ needs.integration-stress-1.result }}" == "failure" ]] || \
           [[ "${{ needs.integration-stress-2.result }}" == "failure" ]] || \
           [[ "${{ needs.integration-system.result }}" == "failure" ]]; then
          echo "One or more integration test suites failed"
          exit 1
        fi
        echo "All integration test suites passed successfully!"

  # Performance tests
  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"
    
    - name: Download built binary
      uses: actions/download-artifact@v4
      with:
        name: test-binaries
        path: target/release
    
    - name: Make binary executable
      run: chmod +x target/release/kotadb
    
    - name: Run quick performance test
      run: |
        # Quick performance smoke test - just verify the binary works
        ./target/release/kotadb --version
        ./target/release/kotadb insert test/doc.md "Test Document" "Test content"
        ./target/release/kotadb get test/doc.md
        ./target/release/kotadb list
        ./target/release/kotadb stats
        echo "✅ Basic operations working"
      env:
        CI: true

  # Container build - can run in parallel
  container:
    name: Container Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build container (Alpine-compatible without ONNX)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: kotadb:ci-test
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Documentation build - can run in parallel
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "docs"
    
    - name: Build documentation
      run: cargo doc --no-deps --all-features
      env:
        RUSTDOCFLAGS: "-D warnings"

  # MCP Package Integration Tests
  mcp-integration:
    name: MCP Package Integration Tests
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "ci-build"
    
    - name: Download built binary
      uses: actions/download-artifact@v4
      with:
        name: test-binaries
        path: target/release
    
    - name: Make binary executable
      run: chmod +x target/release/kotadb
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Check if MCP package exists
      id: check_mcp
      run: |
        if [ -d "kotadb-mcp-package" ] && [ -f "kotadb-mcp-package/package.json" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Cache npm dependencies
      if: steps.check_mcp.outputs.exists == 'true'
      uses: actions/cache@v4
      with:
        path: kotadb-mcp-package/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('kotadb-mcp-package/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install MCP package dependencies
      if: steps.check_mcp.outputs.exists == 'true'
      working-directory: kotadb-mcp-package
      run: |
        # Remove postinstall script temporarily for CI
        npm pkg delete scripts.postinstall 2>/dev/null || true
        npm ci
    
    - name: Build MCP package
      if: steps.check_mcp.outputs.exists == 'true'
      working-directory: kotadb-mcp-package
      run: npm run build
    
    - name: Run MCP unit tests
      if: steps.check_mcp.outputs.exists == 'true'
      working-directory: kotadb-mcp-package
      run: npm run test:unit
    
    - name: Run MCP integration tests
      if: steps.check_mcp.outputs.exists == 'true'
      working-directory: kotadb-mcp-package
      run: npm run test:integration
      env:
        KOTADB_BINARY_PATH: ../target/release/kotadb
    
    - name: Generate MCP coverage report
      if: steps.check_mcp.outputs.exists == 'true'
      working-directory: kotadb-mcp-package
      run: npm run test:coverage
      continue-on-error: true

  # Code coverage - runs in parallel, not dependent on other tests
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: "coverage"
    
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    
    - name: Generate code coverage
      run: |
        # Clean any previous coverage data
        cargo llvm-cov clean --workspace
        # Generate coverage with explicit settings
        cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && success()
      with:
        file: lcov.info
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
      continue-on-error: true