name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CLAUDE.md'
      - 'AGENT.md'
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then
            pip install -r docs/requirements.txt
          else
            pip install mkdocs-material
            pip install mkdocs-minify-plugin
            pip install mkdocs-git-revision-date-localized-plugin
            pip install mkdocs-awesome-pages-plugin
            pip install mkdocs-macros-plugin
            pip install mike
          fi

      - name: Configure Git for Mike
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch gh-pages branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git fetch origin gh-pages --depth=1 || true

      - name: Deploy development documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Deploy main branch docs as 'dev' version
          mike deploy --push --update-aliases dev
          
          # Ensure latest is still the default
          mike set-default --push latest || mike set-default --push dev

      - name: Build documentation for PR preview
        if: github.event_name == 'pull_request'
        run: mkdocs build --verbose

      - name: Upload artifact for PR preview
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: docs-preview
          path: ./site

